### ISSUE TITLE
Todo (zeffii)

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#118]
I'm drawing up this list to keep track of things I want to complete before other random stuff.
  
- [x] Node to turn (verts+edgpol) into dashed edges, creating new verts+edges (dropping polys)
    - [x] exists as 'dashed_edges.py' in `node_scripts/zeffii/`
    - [ ]  use a string representation, or pick from dropdown.
    - [ ]  use slider for scale (scale is relative to world)
    - ![image](https://cloud.githubusercontent.com/assets/619340/5792567/0301d7ac-9f1f-11e4-83a8-2a66e6c9f54f.png)

- [ ] Script Node (Text Editor addon) to generate clone of current as `current_file_CLONE_HHMM`
    - This would enable something like a versioning system, especially useful for code experiments
which may span several similar files sequentially or parallel.

(**low priority**)  

- [ ] profile node implement even spread on bezier spline using vector interpolation, this makes the node dependent on numpy. decide.
- [ ] update Intersect Edges  
    - add tolerance setting to Intersect Edges  
    - add "touching" boolean (currently intersections are limited to X and not T )  
  
(**on hold, partially implemented or implemented but not committed**)

- [ ]  3d cursor node
- [ ]  Grease Pencil In node  
    - [x] select from all available grease pencil layers / strokes in the current .blend
    - [ ] After selection cache immediately?  
- [x] Empty Node https://github.com/nortikin/sverchok/issues/188  
- [x] finish 'inset specials' node (now a branch)
    - [x] inset amount (relative, but absolute should be possible in some sense)
    - [ ] inner face (keep / remove)
    - [ ] axis vector + distance scalar to push inset vertices 
_long term_

- [x] 3d L-system Node   (I implemented this as a [nodescript](https://github.com/zeffii/weblog/blob/master/blends/experimental/3dLsystem_sverchok_ext1.blend), elfnor also introduced an alternative implementation as a proper Node)
- [ ] plot stuff like http://stackoverflow.com/a/4687582/1243487
  

_**done, presently in beta**_

- [x] dump current node_tree to json, and generate from json.
- [x] Viewer Draw Extended 
- [x] rounded rect using phymec's 0.3 code 
- [x] Instancer Node https://github.com/nortikin/sverchok/issues/208
- [x]  _barely beta_ [stethoscope](https://github.com/nortikin/sverchok/issues/243)
     This node shouldn't go on as beta for too long. The main reason it's not on the fast-track to node-proper is because I'm not sure how to format the data usefully. With DebugPrint node it's easy: "just spit out the data". But with BGL render it needs to be formatted and rounded so as not to overwhelm user or processor. The problem is not displaying the data, it's how to display the data in an abbreviated form in a meaningful way.

- [x] [Eval Node](https://github.com/nortikin/sverchok/issues/257#issuecomment-47518977) 
    - [x] add `=eval_text`   (function, internal file, update)
    - [x] add `=read_text`  (internal_file)

_**done**_

- [x] Simple 2pt bezier node (single segment)
- [x] Simple 3pt arc node (single segment)
- [x] Vector Math 2 Node, add Scalar `vector * x` and `vector * 1/x`  .
    - this node is essentially finished, but I will be tested for another while before it replaces the original vector math node.
    - this node is also getting performance boosts.
- [x] SN should have an example about how to refresh imports
      I didn't figure out until a few minutes ago that scripted node could load my own local
      python modules. This means i can offload some work to code written in my favourite Text Editor     (Sublime)  https://github.com/nortikin/sverchok/issues/85#issuecomment-44269679  
- [x] make ui_operator example that deals with incoming socket data  
- [x] Bmesh view revisit
    - [x] ....pick new random mesh name 
    - [x] ....select all generated meshes
    - [x] ....pick base material
- [x] Gtext node https://gist.github.com/zeffii/063763a6b5fc64544f4f
    - [x] create bounds dict to map the width of each glyph
    - [x] use spacing param to space relative to this.
    - [x] prelim typeface
    - [x] prelim drawing code
    - [ ] tokenizer for symbols (maybe \d = degree,  \D = diameter, \r = radius ..etc)
    - [x]  transplant code into a donor node
    - [x]  make latin+cyrillic+extras remap. 
    - [x]  build primary latin+cyrillic+extras font face 
- [x] intersect edges node doesn't remove original edges, it should
- [x] fix generic node_script input, right now nested listed are not handled appropriately
- [x] debug print node ( printing incoming sockets directly to stdout, like viewer Text but without expectations of incoming data formatting ) [done by @ly29 not commited yet](https://github.com/nortikin/sverchok/issues/118#issuecomment-42922586)
- [x] fix default node values for ScriptNode  
- [x] update index viewer
    - add edges + faces to index viewer  
- [x] make kb shortcut for TextEditor to convert sv_main defaults to a new in_scokets declaration
   ```
   def sv_main(verts=[], dist=1.1, strength=1.0):
   ```
   can easily be parsed and turned into in_sockets list.
- [x] ScriptNode to get regular import styles, ie: place imports before `def sv_main()`. having a new import per iteration was a bad idea from the start  
- [x] ScriptNode to allow 'faux' operator buttons, to action functions.
- [x] Implement user defined background+vert+edge+face colours in the N panel (6 colours is too clunky for node UI)
