### ISSUE TITLE
Todo (ly)

### ISSUE THREAD

**Issue by ly29** [nortikin/sverchok#119]
- [x] ~~Clean up util.py~~ Further work needed, factor out things that doesn't need to be called by nodes...
- [x] update function, ~~document~~ #121 and work out issues. #152 #146 #144 #135 #123 - 
- [x] socket cache, finish work. But first discuss #128 #147 
- [x] Fix Text In out. ~~Reload, stability~~, pretty printing json.
- [x] Finish VerticesSort. Axis sort, possible to sort only vertices without mesh data.
- [ ] Finish Adaptive Edges. Different ways to align edges. Reuse existing verts to really connect edges. Scaling along, cross from edge.
- [x] Preferences and Debug Panel
- [x] Compcat UI Socket UI transistion #147 
- [ ] The missing List Nodes
   - [x] List Split
   - [ ]  Stride in List Slice
   - [ ] List Sort, sort by user index
   - [x]  Masked Join
   - [ ]  Index Separate/Dispatch (namning?) like List Mask
- [x] Expose timings system. Heat map suggested, sounds good.
- [x] Revisit wifi nodes, in general way.
- [x] Float Series Creation #164 
- [x] Doubles output in remove doubles

**Comment by ly29** [comment]
This is so old I will just close it.
