### ISSUE TITLE
Todo(nikitron)

### ISSUE THREAD

**Issue by nortikin** [nortikin/sverchok#120]
- [ ] https://github.com/nortikin/sverchok/issues/894 text out to be updated
- [ ] css table of help sphinx
- [ ] https://github.com/nortikin/sverchok/issues/477 sublevels to integrate to all the nodes
- [ ] music analizer for midi or something to output values
- [ ] !(not remember what i ment) circles on vertices to produce holes - under development now
- [ ] to integrate solution http://www.blenderartists.org/forum/showthread.php?339872-Addon-Map-via-UV&
- [ ] to integrate solution http://blenderartists.org/forum/showthread.php?241950-A-Script-to-Skin-a-Point-Cloud-%28for-Blender-2-6x-or-Later%29
- [ ] to integrate solution http://blenderartists.org/forum/showthread.php?348432-Addon-Edge-Roundifier-mesh-modeling-tool-for-building-arcs-on-selected-edges&highlight=sverchok
- [ ] to set OpenGL light and material for Viewer Draw. In place of ugly solution. Progess `20%`
- [x] to send money to goosberry or to invest in sverchok propaganda (google ads)
- [x] Lines connection to be able make real loft - as in looptools, so we could define subdivision and than connect parametrically all vertices. it is usefull for many cases.
- [x] Panel in 3D that represents manipulators floats and integers from layouts to use in 3d window and change parameters from tool panel. thouse we can make layout, let somebody download and use as usual addon, not as layout. he can not even open nodes layout... But we need make boolean in float and integer nodes that allows us embed parameter to sverchok panel in 3d toolshelf
- [x] List append node, List extend node, List insert node
- [x] List sum levels add
- [x] maybe all cache and handles must be on top to see them all to be able manage
- [x] debug regime. Linus made it!!!!!!!!!!!!!!!!!
- [x] extend file "for_developers" to be more clear
- [x] colors of nodes to be in one format - https://github.com/nortikin/sverchok/issues/274
  - red - is error
  - green - input
  - orange - output
  - bluish - all text nodes
    for this reason i should make default colors veriables and maybe decorators or something (need to find out of decorator first and try to do it)
- [x] data trees multyoutput separator node (Separator node) to make all object/verts/etc, depending on level, to go to separate socket
- [x] auto import nodes to _init_.py
- [x] !!! make button in toolbox to get new node on fly and register it ( blender_file_browser -- Copy_file_to_addon_folder -- set_relative_path_to_addon_path -- import_and_register_node_to_be_able_insert_it_in_c urrent_layout )
  Made but with F8 new reimport in init. thanks refactoring
- [x] make panel with properties, that will appear as sliders in this panel from particular float/int/listinput nodes, so in this nodes need to be boolean flag that defines whether it property needs to be in sverchok manipulation panel. that way we can make layouts and from 3d view to change items as with simple addon. so, that way we could make own addons inside svershok. This allows user who not deal with nodes to download layout and use it.
- [x] Make improvements of text viewer, delete loose node and other (my todo)
- [x] Decompose node to do completely
- [x] матриц генератор, задаваемый тремя векторами, одним достаточно, другие ортогонально угадываются, длина вектора - масщтаб, положение вектора в пространстве - поворот.
- [x] узел-очиститель списка от нулевых данных, которые получаются при рассечении предварительно рассечённого объекта, так треугольники бывают не замкнутыми или вершины не найдеными, в общем, бывает.
- [x] Subdivide and produce useful topology Topology is main feature. needed node that takes vertex items, that belong to exact polygon. made by mask indexes in/out mask
- [x] generators uv direction, sublevel to all generators and defaults to false
- [x] custom text in 3d
- [ ] data structure new, universal socket and other issues to discuss - https://github.com/nortikin/sverchok/issues/118#issuecomment-42756740 https://github.com/nortikin/sverchok/issues/184
- [ ] Sv prefix renaming old classes to this standart
- [x] directories hierarhy and autoimport. maybe to make folders separately for modifiers and others?  https://gist.github.com/nortikin/8f75694171ef6cdeff90
- [ ]  material socket
- [x] узел группирования по маске. Вот есть предмет, шар. нам надо UV поменять. что для этого сделать - flip list, но флипать надо между уровнями групп вершин. а для этого их надо сгруппировать. То есть, если у нас U6,V12, то сгруппировать вершины по 6, затем флипнуть, так получим группы по 12, но всего групп 6,  было 12 групп по 6 вершин. То есть узел флип найдёт своего напарника "и они уйдут в закат"
- [x] Get Bounding Box Center Point (BBOX CENTER) => would be nice to have setup that spit out Bounding Box,
- [x] Get the average position based on all vector.
- [ ] Vectorization in two directions line defined scale between vectors vectorized or objects count vectorized. to prepare data have to use this form [ [ [0, 1, 20.2, 1.5], [1], [12,13,14,15,11] ] ] to make three objects with vectorized input. For that needed tools to manipulate levels as toy.
- [x] Fractal node - thanks Elfnor for lsystem
- [x] Viewer Draw sorting by name implementation
- [ ] Sorting node reordered indexes output!!!!! important
- [x] Scale/Rotate/Mirror Vertices... nodes needed
- [x] Volume calculator!!!!

**For versions after 1.0.0**
- [x] генератор сплайнов
- [x] нахождение точки на сплайне - interpolation vertices
- [ ] Вместе с тем, надо добавить тип сокета - кривые. Кривая определяется не так как линия, 
  а двумя рычагами и узлом, итого три вектора на точку. Можно сделать кривую как линию, затем 
  сконвертировать и сгладить, автоматически выстроив красивенько. И так и будет генерироваться 
  кривая из векторов. Но как передавать значения? Если мы считаем формулами эту безье, то 
  нам нужны специфические библиотеки, и их надо достать, ибо АПИ не имеет нужных 
  инструментов (нахождение точки на кривой... это проблема, каждый разработчик решает по-
  своему), и также надо уметь замыкать кривые, а от этого меняется геометрия и нахождение 
  точки на кривой и прочее. Рёбра уже не действуют на кривые, рёбра сокет может быть 
  испольован именно для булена - зациклить или нет. В прочем, если мы все данные переводим
  в кэш, то можно использовать вектор сокет, оставив тем самым гибкость пользователю. и 
  маркировать в кэше тип данных. Это всё касается версии 0,4,0. 
- [ ] IFC format for BIM export. basics for bmesh viewer m3
- [ ] when bmesh viewer rename object it has to not delete object, but delete. For modifiers support. or make stack of modifiers for bmesh viewer to make auto modifier assigning.

**Comment by nortikin** [comment]
IFC format implementation with bmesh viewer and baking - all needed parameters to implement as sockets

**Comment by nortikin** [comment]
http://blenderaddonlist.blogspot.de/2015/05/addon-asset-flinger.html
ideas

**Comment by nortikin** [comment]
outdated
