### ISSUE TITLE
todo in b28_prelease_master

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#2537]
Sverchok for Blender 2.8 has come a long way, but in reality the Pullrequest could stay open indefinitely -- and I don't want that -- no one wants that. But the reality is that this lets us make changes that would be difficult to justify in `2.79` (for fear of breaking stuff).

Some features will need to be fixed later, but most of the real core of Sverchok has been working in `b28` for a while.  The list of todo items doesn't seem to have an end, but the list of things that really need to be fixed to give Sverchok a polished user experience is not so long any more.

The list (as I see it - this is not the list of items still unticked in the [pullrequest](https://github.com/nortikin/sverchok/pull/2299) or https://github.com/nortikin/sverchok/issues/2427):

- [x] (must) layout utility `prop_search` when used to pick a filename ~works only by fluke~
     - ~this was changed in late 2.79 builds, prop_search will store the `filename+num_users` in the string, It might be necessary to implement an `enum` based dropdown. (the downside to that is that pointerproperty would store the correct name if the textfile was renamed... -- in practice i have almost never renamed a file...)~
  - this no longer appears to be a problem 
- [x] (must) `obj_helper` (for Object generating nodes) must make 
     - unique collection names (per node) / object names
     - user collection inside collection (instead of old group)
- [x] (must) node.copy  should be (as discussed in other threads) doing more to ensure a new node isn't stuck in Error colours.
- [x] (must) tests.. tests need to be functional again [see pullrequest](https://github.com/nortikin/sverchok/pull/2538)
- [x] (must) auto fix nodeview scale/dpi  .. how do other add-ons do this?!
```python
# getDpiFactor and getDpi are lifted from Animation Nodes :)

def get_dpi_factor():
    return get_dpi() / 72

def get_dpi():
    systemPreferences = bpy.context.preferences.system
    retinaFactor = getattr(systemPreferences, "pixel_size", 1)
    return systemPreferences.dpi * retinaFactor
```

- [ ] (optional) all node classes should be prefixed with Sv
     - some older nodes don't do this at all, and some nodes just use `sv`
     - for consistency
- [ ]  (optional) Menus and node categories should really be aligned. For sanity i propose no sub-sub menu but rather better main menus. This is a whole topic by itself  
- [ ] (optional) The `List`  categories could be reduced a lot by allowing fewer List nodes, but having a node called "List operations", which would do things like `Trim, Pop, Zip, Append Extend, Wrap, Unwrap, Reverse` -- much like the Math node has modes. The list menu is the hardest to comprehend (i too struggle with the abundance in those lists, when i can write a simple statement in Python...with no complexity-- if that makes new users uncomfortable i will always agree with them )

**Comment by portnov** [comment]
@zeffii  is this issue still actual?

**Comment by zeffii** [comment]
i need help with the `node.copy` stuff.

**Comment by zeffii** [comment]
or rather, i need to get the sense that i'm not the only one bothered by it . then I don't mind assisting/figuring it out/ testing.

**Comment by zeffii** [comment]
and of those things that are listed.
- node classes to get `Sv` prefix would be considered are good practice housecleaning step 
- the menus and dirs,  
     - still not a solved problem. I worked for a while using Lite Menu with an entirely (what seemed to me) sane menu structure, but I found it hard to find nodes compared to the old/current structure (.... or the quick search! )
- List categories, listed as optional, is also not a porting issue, but UX/UI , not unimportant.. but doesn't fuel my fire either.
- obj_helper. this I do think is important, its progress is impeded only by lack of discussion / or maybe it is fine already?
