### ISSUE TITLE
New Todo

### ISSUE THREAD

**Issue by zeffii** [nortikin/sverchok#914]
I will periodically remove comments from this thread (including my own) - don't be offended. I want it to be a snappy read.

- [x] random number generator [discussion thread](https://github.com/nortikin/sverchok/issues/978)
- [x] snlite [discussion thread](https://github.com/nortikin/sverchok/issues/942)
- [ ] ~add curve_eval node (using `template_curve_mapping` ui)~
- [ ] attractor node ( pass a mesh with 1 or more additional points + weights + effec radius + (maybe falloff) )
- [ ] skin modifier 
  - retain user added modifiers
  - proper remove doubles to take radii into acount
  - x y support for radii
- [ ] alternative recalc normals ( with attractors, maybe pos / neg )
- [ ] _list modifier_ node new modes
  - Accumulate Sum zerofirst
  - Drop Repeat Topology
    
The above aren't listed in order of importance.

**Comment by zeffii** [comment]
UX dilemma , if people (like me) will always be copying the URL to clipboard prior to pasting the Gist Id, then why even have the Text input field at all ? Would happily remove.. or make less prominent..

**Comment by nortikin** [comment]
https://gist.github.com/117a870bb100c147f531733d637a49d2

**Comment by zeffii** [comment]
is the frame not appearing in the correct place?

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/19320939/aac96a9a-90b3-11e6-9bea-ae2ff64c9b2b.png)

**Comment by zeffii** [comment]
Unfortunately it does seem to need a Node based Material as an entity from which to take the compiled Curve UI. Meaning, each Eval Curve node would need a shadow RGB Curve Node. (not a big deal, but also hacky : / ) ... but also kinda cool.

**Comment by zeffii** [comment]
here is the demo implementation..
```
    def draw_buttons(self, context, layout):
        tnode = bpy.data.materials['Material'].node_tree.nodes['RGB Curves']
        layout.template_curve_mapping(tnode, "mapping", type="NONE")


    def process(self):
        i = self.inputs
        o = self.outputs

        if not o['points'].is_linked:
            return

        points = i['points'].sv_get()

        rock = []
        for i in points:
            for p in i:
                tnode = bpy.data.materials['Material'].node_tree.nodes['RGB Curves']
                f = tnode.mapping.curves[3].evaluate(p)
                rock.append(f)

        o['points'].sv_set([rock])

```

**Comment by zeffii** [comment]
![image](https://cloud.githubusercontent.com/assets/619340/19322998/6bbc36e0-90bb-11e6-8d3f-475817d5d81a.png)

**Comment by nortikin** [comment]
animation nodes have it and it works.

**Comment by enzyme69** [comment]
Yes I always want this in Sverchok :)

-- 


------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au

**Comment by zeffii** [comment]
there's gotta be a way to create the right property group for the template to display without also needing a cycles Material, but if there isn't then the code we'll use will look very similar to the AN falloff node (i've looked.. it's a logical approach to the limitations)

**Comment by zeffii** [comment]
I do want to add some presets in the form of buttons, and maybe further defaults in the form of a dropdown in `draw_buttons_ext` (or hidden by default on `draw_buttons`.)

**Comment by zeffii** [comment]
### Skin Mesher

Moving the modifers for Skin Mesher may be trickier

`obj.modifiers[1].bl_rna.properties[9].identifier` does give the property name, so in lieu of a proper `.move` or `.new(position=modifier_index, type, name)` , some rudimentary copy code could be made

```python
mod_dict = defaultdict(dict)
for modifier in obj.modifiers:
    for prop in yield_real_props(modifier.bl_rna.properties):
        # store  (Name, Type) : {pros: val, prop, val....}
        mod_dict[(modifier.name, modifier.type)][prop] = getattr(modifier, prop)
```
this may even store object references when modifier contains such thing, like Offset Object. in Array.  I'm still hoping there's nicer modifier rearrange code out there that doesn't rely on bpy.ops.move

**Comment by nortikin** [comment]
https://gist.github.com/nortikin/a94e2ec06089989f5302698791f465f2
yula generator
@enzyme69 it is as creature generator

**Comment by enzyme69** [comment]
It looks like Spin Toy, Nikitron.

**Comment by zeffii** [comment]
hmm, I realize that remove doubles and verts.layers.skin won't work because the mesh won't have skin_vertice radii at that point, (unless I can write to that layer...  oh.. that might work..)

**Comment by zeffii** [comment]
# Random Number Generator

I want this generator to be versatile

I propose a generator that can: 
- take a count ( vectorized )
- output Int or Floats. within a range (vectorized)
- have a bias feature (not sure how to implement yet, either via a Enumerated Curve Set or a Formulate string )

**Comment by zeffii** [comment]
# _note to self_

snlite needs a way to store datapoints for custom draw UI elements, it might have to be excplicit and part of the preprocessor.. unsure about this.

```
"""
in .. .. ..
out .. .. ..
draw some_func
store_ui material_name node_name (bl_idname)
"""
```
if `bl_idname` is omitted , then the default `ShaderNodeRGBCurve` ui element is assumed. Else, well then some custom UI save/load function can be loaded. 

Load / Save for RGB Curves UI
```
# this snippet stores, restores all pertinent data in a RGB Curves node


```

**Comment by zeffii** [comment]
```
ui_storage = Material_name, node_name
```
or
```
ui_storage = Material_name, node_name, bl_idname
# (mat_name: "Material_name", node_name:"RGB Curves", bl_idname: "ShaderNodeRGBCurve"'
```

**Comment by zeffii** [comment]
curve mapping storage
```
import bpy

m = bpy.data.materials.get("MyMaterial")
node = m.node_tree.nodes['RGB Curves']

out_list = []
for idx, curve in enumerate(node.mapping.curves):
    points = curve.points
    out_list.append([(p.handle_type, p.location[:]) for p in points])
print(out_list)

```

**Comment by zeffii** [comment]
checking one this latest voxel video by jimmy.. maybe we should make a 3dgrid node, it's a primitive..
https://gist.github.com/9dd1e1dfb2bb105e4484dd40ad854541

**Comment by zeffii** [comment]
also..iojson needs to force trigger the dupli-instancer node at the end..

**Comment by zeffii** [comment]
stethoscope mk2 ?

a few things bug me about this node, it's time to fix this...  though possibly the two nodes might live side by side for a while, the new node might have features that people don't need.

new node
- it should have a background (like indexviewer)
- allow DPI adjustment / font size
- include options to round floats to conserve space
- it should have options to select level and index (like ListItems)
bonus if this happens fast.

**Comment by enzyme69** [comment]
Thanks Zeffii for kindly checking my live noding.

with Grid 3D stuff can we make it more magical like MagicaVoxel where we
can "offset" in X Y Z

**Comment by zeffii** [comment]
restoring modifiers between updates. This will have to be a switch, because I think it's going to be a slow operation.
```python
import bpy

modifier_sequence = []
obj = bpy.context.active_object

for modifier in obj.modifiers:
    props = [p.identifier for p in modifier.bl_rna.properties if not p.is_readonly]
    single_mod_dict = {p: getattr(modifier, p) for p in props}
    modifier_sequence.append([modifier.type, single_mod_dict])


print(modifier_sequence)
```
