### ISSUE TITLE
ROADMAP, bugs, todo / 2016-11-09

### ISSUE THREAD

**Issue by nortikin** [nortikin/sverchok#955]
SUBJ:
What to do for reach 1.0 and what steps we need?

todos personal:
https://github.com/nortikin/sverchok/issues/120
https://github.com/nortikin/sverchok/issues/914
https://github.com/nortikin/sverchok/issues/119

- [x] - 1. see that layout-convert sockets node lost.
Is it somewhere?
- [ ] -  2. np.array node from kosvor have no adaptive socket, so i have to convert. It is needed to be adaptive.
Kosvor also made thi mistake in all his nodes.
- [ ] - 3. vertex group weight has no object socket input as others also from kosvor in scene section + dubli instancer, mesh instancer, object remote control, not saying of alpha nodes
- [ ] - 4. first of all icons have to be in menu sections, it is main for show them by default
- [ ] - 5. documentations for some nodes in modifier section ARE NOT FINISHED OR NAMES DISMATCH (voronoi 2d, delaunay, wireframe, solidify, adaptive edges, limited dissolve, ALL name-dismatched + lost docs for duplicate along edge), number section (easing HAVENO docs and map range,math(sic!),range float name-dismatch), vector section (vector noise, vector sort, Xdoubles are name dismatch +  vector interpolation mk2, mk1 HAVENO docs), matrix (interpolation, deform, input, euler, in and out are names-dismatch), list (mask out and mask in not in corresponding folders, modifiers, also not corresponding, names are not matching for most), text (textin and out not match names), also not matching names for most of scene, wifi inout also other names, network have no docs at all.
- [x] - 6. templates are available when node tree not opened. it is mistake. it makes error. How to make templates to be shown and when pressing to create new node tree and show it?
- [ ] - 7. have the generator-image node to be removed?
- [x] - 8. scripted nodes have to be in generator extended as mk1 mk2 mk3 all three presented
- [ ] - 9. do we need interpolation mk1 still?
- [ ] - 10. i have to make pattern inerpolation node separated with separated algorythm
- [ ] - 11. needed dimentions node (simple one)
- [ ] - 12. Vectorize all in two levels at least. as per object + per evrtices in object. maybe more. we need automotisation for that thing
- [ ] - 13. All the things have to be unified, as levels in generators (separate levels, line node etc), in modifiers (modifiers handle levels as recursion if possible)
- [ ] - 14. Object Sockets not work properly if we remofe mesh with bmeshViewerMK2, so we need handle soft way of updating geometry. it is MUSTHAVE feature. To handle modifications with geometry as UV layers node and weight paint and vertex paint etc. Soft way not just keed vertex count, but also keep vertex count by default with handle concenred errors and so on. with maybe recalc vertices button maybe.
- [ ] - 15. @enzyme69 asked https://github.com/nortikin/sverchok/issues/964#issuecomment-262371226 here for motion path
- [ ] - 16. Color nodes series RGB,HSV,etc in out convert
If we solve this we can follow 1.0 version (full documentation+templates+kosvor fixes)
- [ ] - 17. Interpolation nodes have same functions - to separate them to utils
- [ ] - 18. ObjectIn have to have hidden sockets for vertex groups, colors, shapekeys, etc with enum popups. If object in to be only for object insertion than no vertices needed, but now we have double-functions with get object and so on.
- [ ] - 19. particles node have to have also hidden sockets. it is the same principle, so needs same definition or decorator to find properties. OR to pack all particle systems to separate sub-objects?

Or we should do something with 0.6 0.7 0.8 0.9 versions?
or to make new sockets for version 1.0 and current list will work as 0.7 i.e.?

**Comment by zeffii** [comment]
>  - 6. templates are available when node tree not opened. it is mistake. it makes error. How to make templates to be shown and when pressing to create new node tree and show it?

this is down to a poll function..

**Comment by zeffii** [comment]
```python
def node_templates_pulldown(self, context):
    if context.space_data.tree_type == 'SverchCustomTreeType' and context.space_data.edit_tree:
        layout = self.layout
        row = layout.row(align=True)
        row.scale_x = 1.3
        row.menu("SV_MT_layouts_templates", icon="RNA")
```
prevents the visibility of the templates button, until there's a visible edit tree..   this prevents that error.. , but if you want the template button to be visible with no edit_tree active, then we'd need to modify `'node.tree_importer_silent'` operator to create tree first then import.

**Comment by zeffii** [comment]
i'll fix that one :)

**Comment by zeffii** [comment]
https://github.com/nortikin/sverchok/pull/956  fixes it I think..

**Comment by zeffii** [comment]
@nortikin  regarding documentation / number 5 , I understand that this relates to the bl_label of Nodes currently not always corresponding with the Name on the Node UI within the documentation and pictures. ? Definitely this needs to be fixed in the documentation and not in the nodes themselves.  Bit of a pain in the butt :)

**Comment by nortikin** [comment]
i made some time ago some docs, will go on, nothing special, just time.

**Comment by nortikin** [comment]
- [ ] - 12. Vectorize all in two levels at least. as per object + per evrtices in object. maybe more. we need automotisation for that thing

**Comment by nortikin** [comment]
- [ ] 13,14 points.
What you think?

**Comment by zeffii** [comment]
some rewrite of BMViewMK2 is probably due.  MK3 i am thinking about.

I don't know how well the Objects out of BMVMK2  was tested, likely it can be fixed for the described scenario _before_ introducing MK3.

**Comment by zeffii** [comment]
## regarding 14:

the goal of SVRedux was implement a more unified interface, but I think the simultaneous implementation of a different way to write nodes was a distraction (now... )

**Comment by ly29** [comment]
### For 12:

see #1112 as possible way forward.

**Comment by DolphinDream** [comment]
If no one is working on a color node (random color node) I would like to start working on this. Any guides, suggestions for where to start are appreciated.

**Comment by zeffii** [comment]
@DolphinDream 
> If no one is working on a color node (random color node) I would like to start working on this. Any guides, suggestions for where to start are appreciated.

- Look at Vector In and Out,  for combine / separate  code.
- https://github.com/nortikin/sverchok/tree/color_nodes_v1 might be of some interest ( I added a new socket type which was overkill, using StringsSocket will work fine )

**Comment by nortikin** [comment]
docs in process by Ivan

**Comment by nortikin** [comment]
close for good
